# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the for_deploy branch
  push:
    branches: [ for_deploy ]
  pull_request:
    branches: [ for_deploy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: npm ci
      - name: customize
        run: npm run install:custom
      - name: generate
        run: npm run generate
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
      - name: build
        uses: actions/upload-artifact@v2
        with:
          name: blog
          path: dist
          retention-days: 1
