name: deploy
on: [push]
jobs:
  start-ipfs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: npm ci
      - name: customize
        run: npm run install:custom
      - name: generate
        run: npm run generate

